import type { Vendor } from './types';

// This data is used to seed the database if the vendors collection is empty.
// It is transformed to match the Vendor schema in backend.json.
export const seedVendors: Omit<Vendor, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: "Precision Auto Qatar",
    address: "Street 10, Industrial Area, Doha",
    rating: 4.8,
    reviewCount: 125,
    services: ["Engine Repair", "Brake Service", "AC Repair", "Full Detailing"],
    imageId: "garage-interior",
    latitude: 25.21,
    longitude: 51.48,
    status: "Approved",
    type: "Garage",
    city: "Doha",
    country: "Qatar",
    phoneNumber: "+974 4455 6677",
    email: "contact@precisionauto.qa",
  },
  {
    name: "Doha Car Experts",
    address: "Salwa Road, Doha",
    rating: 4.5,
    reviewCount: 88,
    services: ["Oil Change", "Tire Alignment", "Diagnostics"],
    imageId: "garage-exterior",
    latitude: 25.25,
    longitude: 51.47,
    status: "Approved",
    type: "Garage",
    city: "Doha",
    country: "Qatar",
    phoneNumber: "+974 4411 2233",
    email: "info@dohacarexperts.com",
  },
  {
    name: "German Auto Specialists",
    address: "Barwa Village, Al Wakrah",
    rating: 4.9,
    reviewCount: 210,
    services: ["BMW Service", "Mercedes Service", "Audi Service"],
    imageId: "garage-interior-2",
    latitude: 25.17,
    longitude: 51.55,
    status: "Approved",
    type: "Garage",
    city: "Al Wakrah",
    country: "Qatar",
    phoneNumber: "+974 4499 8877",
    email: "service@germanauto.qa",
  },
  {
    name: "Quick Lube Center",
    address: "C Ring Road, Doha",
    rating: 4.2,
    reviewCount: 350,
    services: ["Quick Oil Change", "Filter Replacement"],
    imageId: "garage-exterior-2",
    latitude: 25.28,
    longitude: 51.51,
    status: "Approved",
    type: "Garage",
    city: "Doha",
    country: "Qatar",
    phoneNumber: "+974 4433 4455",
    email: "support@quicklube.qa",
  },
];
