/**
 * build-tokens.mjs — generates platform-specific token files from the shared
 * source in packages/tokens/src/index.ts.
 *
 * Outputs (both committed, so neither app needs a workspace dependency on
 * the other — the two apps are separate git repos):
 *   - src/app/tokens.generated.css      (CSS custom properties, imported by globals.css)
 *   - mobile/lib/theme.generated.ts     (re-exported by mobile/lib/theme.ts)
 *
 * Run: npm run tokens:build
 */
import { writeFileSync, readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

// The token source is plain TS with no imports and only `as const` object
// literals, so it can be evaluated by stripping the type-only syntax rather
// than pulling in a TS compiler just for a build step.
const sourcePath = resolve(root, 'packages/tokens/src/index.ts');
const source = readFileSync(sourcePath, 'utf8');
const evaluatable = source
  .replace(/^export /gm, '')
  .replace(/ as const/g, '')
  .replace(/^\/\*\*[\s\S]*?\*\//m, '');

const tokens = new Function(`
  ${evaluatable}
  return { palette, darkColors, lightColors, radius, spacing, motion,
           statusColorsDark, statusColorsLight, categoryColorsDark, categoryColorsLight };
`)();

const BANNER = '/* GENERATED by scripts/build-tokens.mjs from packages/tokens/src/index.ts — do not edit by hand. */';

// ── Web: CSS custom properties ───────────────────────────────────────────────

function cssVarName(key) {
  return `--qw-${key.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()}`;
}

/**
 * shadcn/ui's primitives consume colours as bare HSL triplets
 * (`hsl(var(--background))` in tailwind.config.ts), so the shared hex
 * palette has to be converted rather than dropped in verbatim — otherwise
 * every UI primitive breaks. Only opaque hex values can be expressed this
 * way; rgba tokens stay available as raw --qw-* vars instead.
 */
function hexToHslTriplet(hex) {
  const normalized = hex.replace('#', '');
  if (!/^[0-9a-fA-F]{6}$/.test(normalized)) return null;
  const r = parseInt(normalized.slice(0, 2), 16) / 255;
  const g = parseInt(normalized.slice(2, 4), 16) / 255;
  const b = parseInt(normalized.slice(4, 6), 16) / 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;
  let h = 0;
  let s = 0;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    if (max === r) h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
    else if (max === g) h = ((b - r) / d + 2) / 6;
    else h = ((r - g) / d + 4) / 6;
  }
  const round = (n) => Math.round(n * 10) / 10;
  return `${round(h * 360)} ${round(s * 100)}% ${round(l * 100)}%`;
}

// Maps shadcn's semantic variable names onto the shared token keys.
const SHADCN_MAP = {
  background: 'background',
  foreground: 'text',
  card: 'surface',
  'card-foreground': 'text',
  popover: 'surfaceElevated',
  'popover-foreground': 'text',
  primary: 'primary',
  secondary: 'surfaceAlt',
  'secondary-foreground': 'text',
  muted: 'surfaceAlt',
  'muted-foreground': 'muted',
  accent: 'surfaceAlt',
  'accent-foreground': 'text',
  destructive: 'danger',
  ring: 'primary',
  'sidebar-background': 'surface',
  'sidebar-foreground': 'text',
  'sidebar-primary': 'primary',
  'sidebar-accent': 'surfaceAlt',
  'sidebar-accent-foreground': 'text',
};

function shadcnBlock(colors, indent = '    ') {
  return Object.entries(SHADCN_MAP)
    .map(([cssVar, tokenKey]) => {
      const triplet = hexToHslTriplet(colors[tokenKey]);
      return triplet ? `${indent}--${cssVar}: ${triplet};` : null;
    })
    .filter(Boolean)
    .join('\n');
}

function colorBlock(colors, indent = '    ') {
  return Object.entries(colors)
    .map(([key, value]) => `${indent}${cssVarName(key)}: ${value};`)
    .join('\n');
}

function statusBlock(statusColors, indent = '    ') {
  return Object.entries(statusColors)
    .flatMap(([status, parts]) =>
      Object.entries(parts).map(
        ([part, value]) => `${indent}--qw-status-${status.toLowerCase()}-${part}: ${value};`,
      ),
    )
    .join('\n');
}

const css = `${BANNER}
/*
 * Two kinds of variable here:
 *   --qw-*            raw shared tokens, for custom styling that isn't
 *                     expressed through a shadcn primitive.
 *   --background etc. shadcn/ui's semantic HSL triplets, DERIVED from the
 *                     same tokens so the component library and custom CSS
 *                     can't drift apart.
 *
 * Plain :root/.dark rather than @layer base — Tailwind's @layer is a
 * build-time directive that only works in a file containing @tailwind
 * base, which this imported file isn't. Ordering does the job instead:
 * globals.css hoists this @import above its own @tailwind directives, so
 * anything globals.css redefines in its @layer base block still wins.
 */

:root {
${colorBlock(tokens.lightColors)}

${statusBlock(tokens.statusColorsLight)}

${Object.entries(tokens.radius).map(([k, v]) => `    --qw-radius-${k}: ${v}px;`).join('\n')}

${Object.entries(tokens.spacing).map(([k, v]) => `    --qw-spacing-${k}: ${v}px;`).join('\n')}

    --qw-motion-fast: ${tokens.motion.fast}ms;
    --qw-motion-base: ${tokens.motion.base}ms;
    --qw-motion-slow: ${tokens.motion.slow}ms;
    --qw-ease-smooth: ${tokens.motion.easeSmooth};
    --qw-ease-spring: ${tokens.motion.easeSpring};

    /* shadcn/ui semantic tokens (derived) */
${shadcnBlock(tokens.lightColors)}
}

.dark {
${colorBlock(tokens.darkColors)}

${statusBlock(tokens.statusColorsDark)}

    /* shadcn/ui semantic tokens (derived) */
${shadcnBlock(tokens.darkColors)}
}
`;

writeFileSync(resolve(root, 'src/app/tokens.generated.css'), css, 'utf8');
console.log('  ✓ src/app/tokens.generated.css');

// ── Mobile: TS module ────────────────────────────────────────────────────────

function tsExport(name, value) {
  return `export const ${name} = ${JSON.stringify(value, null, 2)} as const;`;
}

const mobileTs = `${BANNER}

${tsExport('palette', tokens.palette)}

${tsExport('darkColors', tokens.darkColors)}

${tsExport('lightColors', tokens.lightColors)}

${tsExport('radius', tokens.radius)}

${tsExport('spacing', tokens.spacing)}

${tsExport('motion', tokens.motion)}

${tsExport('statusColorsDark', tokens.statusColorsDark)}

${tsExport('statusColorsLight', tokens.statusColorsLight)}

${tsExport('categoryColorsDark', tokens.categoryColorsDark)}

${tsExport('categoryColorsLight', tokens.categoryColorsLight)}
`;

writeFileSync(resolve(root, 'mobile/lib/theme.generated.ts'), mobileTs, 'utf8');
console.log('  ✓ mobile/lib/theme.generated.ts');

console.log('\nTokens built.\n');
