/**
 * QarWheel seed script — populates 5 real Qatar garages + demo customer.
 *
 * HOW TO RUN:
 *   1. Go to Firebase Console → Authentication → Users
 *   2. Find/create a user with email seed.admin@qarwheel.internal (or any email)
 *   3. In Firebase Console → Firestore → Rules, temporarily add at the TOP of the
 *      match block (inside the outer match): allow read, write: if true;
 *   4. Run: node --env-file=.env.local scripts/seed-demo.mjs
 *   5. Restore the original rules immediately after seeding.
 *
 * ALTERNATIVELY: Open Firebase Console → Firestore and import the exported JSON
 * from scripts/firestore-seed-export.json (generated by this script on first run).
 *
 * Run: node --env-file=.env.local scripts/seed-demo.mjs
 */
import 'dotenv/config';
import { initializeApp } from 'firebase/app';
import { getAuth, signInWithEmailAndPassword, createUserWithEmailAndPassword } from 'firebase/auth';
import { doc, getFirestore, setDoc, serverTimestamp } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};

if (!firebaseConfig.projectId) {
  throw new Error('Missing NEXT_PUBLIC_FIREBASE_PROJECT_ID. Copy .env.example to .env.local first.');
}

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);
const auth = getAuth(app);

const PROJECT_ID = firebaseConfig.projectId;
const API_KEY = firebaseConfig.apiKey;
// Seed user's actual Firebase Auth UID (seed.admin@qarwheel.internal).
// Used as customerId, and as vendor ownerId so isVendorOwner() passes for service writes.
// NOTE: If this seed user doesn't exist yet, it will be created on first run.
const SEED_UID = 'oOI5zUcOjqSgkl1nZV7xV8CfFfF3';
const CUSTOMER_ID = SEED_UID;
const CAR_LAND_CRUISER = 'car_land_cruiser_2022';
const CAR_CAMRY = 'car_camry_2020';
const CAR_PATROL = 'car_patrol_2021';

const VENDORS = [
  {
    id: 'vendor_aab_toyota',
    data: {
      ownerId: SEED_UID,
      name: 'AAB Toyota Main Service Center',
      type: 'Garage',
      description: "Abdullah Abdulghani & Bros — Toyota's flagship authorised service centre in Qatar. 24-bay facility with factory-trained technicians, genuine Toyota parts, and full warranty coverage.",
      address: 'Street 6, Industrial Area',
      city: 'Doha',
      country: 'Qatar',
      phoneNumber: '+97440316000',
      email: 'service@aabqatar.com',
      websiteUrl: 'https://www.aabqatar.com',
      latitude: 25.21443,
      longitude: 51.43446,
      status: 'Approved',
      rating: 4.7,
      reviewCount: 312,
      imageId: 'garage-modern',
    },
    services: [
      { id: 'toyota-oil-change', name: 'Toyota Genuine Oil Service', description: 'Synthetic engine oil, OEM filter replacement, multi-point inspection, and digital service stamp.', duration: 45, price: 380 },
      { id: 'toyota-ac-service', name: 'Air Conditioning Service', description: 'Gas recharge, condenser clean, cabin filter replacement — essential for Qatar summers.', duration: 90, price: 450 },
      { id: 'toyota-brake-overhaul', name: 'Full Brake Overhaul', description: 'Pads, rotors, brake fluid flush, and caliper inspection on all four wheels.', duration: 120, price: 950 },
      { id: 'toyota-60k-service', name: '60,000 km Major Service', description: 'Full 60 k service: timing belt, spark plugs, filters, fluids, and thorough chassis inspection.', duration: 240, price: 2200 },
      { id: 'toyota-tyre-rotation', name: 'Tyre Rotation & Balancing', description: 'Four-wheel rotation, dynamic balancing, and tyre pressure calibration.', duration: 60, price: 180 },
    ],
    inventory: [
      { id: 'toyota-oil-filter', name: 'Toyota Genuine Oil Filter', sku: 'TYT-FLT-001', stock: 120, price: 55, supplier: 'Toyota Gulf' },
      { id: 'toyota-cabin-filter', name: 'Toyota Cabin Air Filter', sku: 'TYT-CAB-001', stock: 60, price: 95, supplier: 'Toyota Gulf' },
      { id: 'toyota-brake-pad', name: 'Toyota Genuine Brake Pad Set (Front)', sku: 'TYT-BRK-F01', stock: 40, price: 320, supplier: 'Toyota Gulf' },
    ],
    reviews: [
      { customerName: 'Khalid Al-Mannai', rating: 5, comment: 'Excellent service, very professional staff. My Land Cruiser was ready ahead of schedule.', date: '2026-05-20' },
      { customerName: 'Sarah Mitchell', rating: 5, comment: 'Best Toyota service centre in Qatar. Genuine parts and transparent pricing.', date: '2026-04-15' },
      { customerName: 'Mohammed Al-Thani', rating: 4, comment: 'Good service overall. Waiting area is comfortable. Took a bit longer than quoted.', date: '2026-03-10' },
      { customerName: 'Priya Nair', rating: 5, comment: 'The AC service was life-saving before summer. Very knowledgeable technicians.', date: '2026-02-28' },
      { customerName: 'James Wilson', rating: 4, comment: 'Professional and courteous. Their digital service record system is very convenient.', date: '2026-01-15' },
    ],
    promotions: [
      { id: 'toyota-summer-promo', title: 'Summer AC Check', description: 'Free AC inspection with any oil service — beat the Qatar heat.', discount: '15%', code: 'AAB-SUMMER26', startDate: '2026-05-01', endDate: '2026-09-30' },
    ],
  },
  {
    id: 'vendor_al_mana_ford',
    data: {
      ownerId: SEED_UID,
      name: 'Al Mana Ford & Lincoln Service',
      type: 'Garage',
      description: 'Al Mana Automotive — official Ford and Lincoln authorised service centre. 36 certified Ford technicians, 7,800 sqm state-of-the-art facility with quick lane, body shop, and express service.',
      address: 'Street 23, Industrial Area',
      city: 'Doha',
      country: 'Qatar',
      phoneNumber: '+97440111222',
      email: 'fordservice@almana.com',
      websiteUrl: 'https://www.almana.com',
      latitude: 25.20205,
      longitude: 51.44531,
      status: 'Approved',
      rating: 4.6,
      reviewCount: 245,
      imageId: 'garage-exterior',
    },
    services: [
      { id: 'ford-oil-service', name: 'Ford Motorcraft Oil Service', description: 'Motorcraft synthetic oil, filter change, brake & fluid level check, and multi-point inspection.', duration: 45, price: 350 },
      { id: 'ford-transmission', name: 'Automatic Transmission Service', description: 'Fluid drain and refill, filter replacement, and shift quality test.', duration: 120, price: 780 },
      { id: 'ford-alignment', name: 'Four-Wheel Alignment & Balancing', description: 'Computer-assisted 4-wheel alignment, dynamic wheel balancing, and tyre pressure check.', duration: 60, price: 250 },
      { id: 'ford-ac-regas', name: 'AC Regas & Sanitise', description: 'R134a refrigerant recharge, leak test, condenser flush, and anti-bacterial cabin treatment.', duration: 90, price: 380 },
      { id: 'ford-battery', name: 'Battery Replacement & Charging', description: 'Motorcraft battery test, replacement with OEM unit, and 12V system health check.', duration: 30, price: 420 },
    ],
    inventory: [
      { id: 'ford-oil', name: 'Ford Motorcraft 5W-30 Synthetic (5L)', sku: 'FRD-OIL-5W30', stock: 80, price: 175, supplier: 'Ford Gulf Parts' },
      { id: 'ford-wiper', name: 'Ford OEM Wiper Blade Set', sku: 'FRD-WPR-001', stock: 50, price: 85, supplier: 'Ford Gulf Parts' },
      { id: 'ford-battery-oem', name: 'Motorcraft Battery 65AH', sku: 'FRD-BAT-065', stock: 20, price: 380, supplier: 'Motorcraft Qatar' },
    ],
    reviews: [
      { customerName: 'Abdullah Al-Rashid', rating: 5, comment: 'Quick lane is genuinely quick. In and out in 40 minutes for oil change.', date: '2026-05-18' },
      { customerName: 'Lisa Chen', rating: 4, comment: 'Very professional team. The waiting lounge is excellent.', date: '2026-04-22' },
      { customerName: 'Ahmed Hassan', rating: 5, comment: 'Booked my F-150 for major service. Everything done perfectly, no surprise charges.', date: '2026-03-30' },
      { customerName: 'Rania Farouk', rating: 4, comment: 'Good experience overall. Staff communicated well throughout the service.', date: '2026-02-14' },
      { customerName: 'Tom Bradley', rating: 5, comment: "Best authorised Ford dealer service I've experienced. Highly recommend.", date: '2026-01-20' },
    ],
    promotions: [],
  },
  {
    id: 'vendor_nissan_service',
    data: {
      ownerId: SEED_UID,
      name: 'Nissan Authorised Service Centre',
      type: 'Garage',
      description: 'Official Nissan service centre operated by Saleh Al Hamad Al Mana Co. Full range of Nissan and Infiniti services with factory-certified technicians and genuine Nissan parts.',
      address: 'Industrial Area, Doha',
      city: 'Doha',
      country: 'Qatar',
      phoneNumber: '+97440224488',
      email: 'nissan.service@almana.com',
      websiteUrl: 'https://www.nissan-qatar.com',
      latitude: 25.21303,
      longitude: 51.43741,
      status: 'Approved',
      rating: 4.5,
      reviewCount: 198,
      imageId: 'garage-interior',
    },
    services: [
      { id: 'nissan-oil-service', name: 'Nissan Genuine Oil Service', description: 'Castrol Nissan-spec synthetic oil, OEM filter, top-up all fluids, 21-point inspection.', duration: 45, price: 340 },
      { id: 'nissan-patrol-ac', name: 'Patrol/Pathfinder AC Service', description: "Full AC system service tailored for Qatar's harsh climate — regas, clean, disinfect.", duration: 120, price: 550 },
      { id: 'nissan-ecu-scan', name: 'ECU Diagnostic Scan', description: 'Full vehicle ECU scan using Nissan CONSULT-3 Plus diagnostic tool with detailed report.', duration: 60, price: 200 },
      { id: 'nissan-suspension', name: 'Suspension Inspection & Repair', description: 'Full front and rear suspension inspection, shock absorber test, and alignment check.', duration: 90, price: 600 },
      { id: 'nissan-timing-chain', name: 'Timing Chain Service', description: 'Timing chain tension check, tensioner replacement if needed, and full fluid change.', duration: 180, price: 1800 },
    ],
    inventory: [
      { id: 'nissan-oil-filter', name: 'Nissan Genuine Oil Filter', sku: 'NSN-FLT-001', stock: 90, price: 50, supplier: 'Nissan Qatar Parts' },
      { id: 'nissan-air-filter', name: 'Nissan Air Filter (V8)', sku: 'NSN-AIR-V8', stock: 45, price: 120, supplier: 'Nissan Qatar Parts' },
      { id: 'nissan-spark-plug', name: 'NGK Iridium Spark Plugs (set of 8)', sku: 'NSN-SPK-IX8', stock: 30, price: 480, supplier: 'NGK Gulf' },
    ],
    reviews: [
      { customerName: 'Hassan Al-Kuwari', rating: 5, comment: 'My Patrol GT5A runs perfectly after the major service. Great value.', date: '2026-05-25' },
      { customerName: 'Fatima Al-Sulaiti', rating: 4, comment: 'Clean facility, courteous staff. Genuine Nissan parts used throughout.', date: '2026-04-10' },
      { customerName: 'David Park', rating: 5, comment: 'Excellent ECU diagnostic service. Found an issue the previous garage missed.', date: '2026-03-15' },
      { customerName: 'Mariam Al-Jaber', rating: 4, comment: 'Reasonably priced and professional. Will return for the next service.', date: '2026-02-20' },
      { customerName: 'Ravi Kumar', rating: 5, comment: 'The Nissan CONSULT diagnostic tool is very thorough. Highly recommended.', date: '2026-01-08' },
    ],
    promotions: [
      { id: 'nissan-free-scan', title: 'Free ECU Scan', description: 'Complimentary ECU diagnostic scan with any major service booking.', discount: 'Free Scan', code: 'NSN-SCAN26', startDate: '2026-04-01', endDate: '2026-07-31' },
    ],
  },
  {
    id: 'vendor_teyseer',
    data: {
      ownerId: SEED_UID,
      name: 'Teyseer Service Centre',
      type: 'Garage',
      description: "Established 1976 — Doha's most experienced multi-brand service centre on Airport Road. 24-hour emergency service, authorised for multiple European and Asian brands, with a full-service body shop.",
      address: 'Airport Road (C Ring Road)',
      city: 'Doha',
      country: 'Qatar',
      phoneNumber: '+97444682683',
      email: 'info@tsc-qatar.com',
      websiteUrl: 'https://www.tsc-qatar.com',
      latitude: 25.2637,
      longitude: 51.5541,
      status: 'Approved',
      rating: 4.8,
      reviewCount: 489,
      imageId: 'garage-bay',
    },
    services: [
      { id: 'tsc-express-oil', name: 'Express Oil & Filter Change', description: 'Any brand, any grade — synthetic or semi-synthetic oil and filter while you wait. No appointment needed.', duration: 30, price: 280 },
      { id: 'tsc-full-detailing', name: 'Full Car Detailing', description: 'Interior deep-clean, exterior clay bar and machine polish, ceramic coating application.', duration: 360, price: 1500 },
      { id: 'tsc-ac-full', name: 'Complete AC System Overhaul', description: 'Full AC service: compressor check, refrigerant recharge, condenser & evaporator clean, cabin disinfection.', duration: 150, price: 650 },
      { id: 'tsc-tyre-service', name: 'Tyre Supply & Fitment', description: 'Supply and fit premium tyres (Michelin, Bridgestone, Pirelli) with balancing and TPMS reset.', duration: 60, price: 850 },
      { id: 'tsc-emergency', name: '24-Hour Emergency Service', description: 'Round-the-clock breakdown assistance including towing, on-site repair, and temporary fixes.', duration: 60, price: 500 },
    ],
    inventory: [
      { id: 'tsc-castrol-5w30', name: 'Castrol EDGE 5W-30 (5L)', sku: 'TSC-OIL-5W30', stock: 200, price: 165, supplier: 'Castrol Qatar' },
      { id: 'tsc-michelin-225', name: 'Michelin Primacy 4 225/60R18', sku: 'TSC-TYR-P4225', stock: 16, price: 420, supplier: 'Michelin Qatar' },
      { id: 'tsc-ceramic', name: 'CarPro Cquartz Ceramic Coat (50ml)', sku: 'TSC-CRM-CQ50', stock: 10, price: 890, supplier: 'Detail Hub Qatar' },
    ],
    reviews: [
      { customerName: 'Omar Al-Farsi', rating: 5, comment: 'Been coming here since 2010. Always reliable, always professional. Best in Doha.', date: '2026-06-01' },
      { customerName: 'Jennifer Adams', rating: 5, comment: 'The 24-hour service saved me when I broke down at 2am. Absolutely life-saving.', date: '2026-05-12' },
      { customerName: 'Yousef Al-Naimi', rating: 5, comment: 'Full detailing service was worth every riyal. Car looks brand new.', date: '2026-04-28' },
      { customerName: 'Ananya Sharma', rating: 4, comment: 'Express oil change really is express. 30 minutes and done, great quality.', date: '2026-03-22' },
      { customerName: 'Marco Rossi', rating: 5, comment: 'Incredible service centre. Knowledgeable staff who service my European car perfectly.', date: '2026-02-10' },
      { customerName: 'Laila Hassan', rating: 5, comment: 'Used them for full AC overhaul before summer. Flawless job, great price.', date: '2026-01-30' },
    ],
    promotions: [
      { id: 'tsc-loyalty', title: 'Loyalty Discount', description: '10% off all services for returning customers. Show your previous invoice.', discount: '10%', code: 'TSC-LOYAL', startDate: '2026-01-01', endDate: '2026-12-31' },
      { id: 'tsc-detailing-promo', title: 'Detailing Summer Special', description: 'Full detailing including ceramic coat at a special rate — protect against the summer heat.', discount: '20%', code: 'TSC-DETAIL26', startDate: '2026-05-01', endDate: '2026-08-31' },
    ],
  },
  {
    id: 'vendor_qauto_vw',
    data: {
      ownerId: SEED_UID,
      name: 'Q-Auto Volkswagen & Audi Service',
      type: 'Garage',
      description: 'Q-Auto — authorised Volkswagen and Audi service facility at Street 41, Gate 59, Industrial Area. 19 working bays, genuine parts, body shop, detailing bays, and certified VAG group technicians.',
      address: 'Street 41, Gate 59, Industrial Area',
      city: 'Doha',
      country: 'Qatar',
      phoneNumber: '+97440158800',
      email: 'service@q-auto.com.qa',
      websiteUrl: 'https://www.q-auto.com.qa',
      latitude: 25.19542,
      longitude: 51.44298,
      status: 'Approved',
      rating: 4.6,
      reviewCount: 176,
      imageId: 'garage-exterior',
    },
    services: [
      { id: 'vw-oil-service', name: 'VW/Audi Longlife Oil Service', description: 'VW 504/507 spec oil (Castrol Edge), OEM filter, AdBlue top-up if applicable, service interval reset.', duration: 60, price: 420 },
      { id: 'vw-dsg-service', name: 'DSG Gearbox Service', description: 'Haldex / DSG transmission fluid replacement, mechatronic unit inspection, and adaptive reset.', duration: 120, price: 950 },
      { id: 'vw-carbon-clean', name: 'Intake Valve Carbon Clean', description: 'Walnut-blast cleaning of intake valves on direct-injection TSI/TFSI engines — restores lost power.', duration: 240, price: 1600 },
      { id: 'vw-brake-service', name: 'Brake Pad & Disc Replacement', description: 'Genuine VW/Audi brake pads and discs, brake fluid flush, EPB electronic caliper reset.', duration: 120, price: 1100 },
      { id: 'vw-ac-service', name: 'AC Regas & Pollen Filter', description: 'R134a/R1234yf recharge, pollen filter replacement, and anti-bacterial evaporator clean.', duration: 90, price: 480 },
    ],
    inventory: [
      { id: 'vw-oil-504', name: 'Castrol Edge 5W-30 VW504 (5L)', sku: 'QAU-OIL-504', stock: 75, price: 190, supplier: 'Castrol VAG Qatar' },
      { id: 'vw-dsg-fluid', name: 'VW DSG7 Transmission Fluid (6L)', sku: 'QAU-DSG-FL7', stock: 25, price: 350, supplier: 'Volkswagen Gulf' },
      { id: 'vw-brake-pad-front', name: 'Audi A6/Q5 Front Brake Pad Set', sku: 'QAU-BRK-A6F', stock: 18, price: 450, supplier: 'TRW Qatar' },
    ],
    reviews: [
      { customerName: 'Tariq Al-Emadi', rating: 5, comment: 'Only place in Doha that truly knows VAG cars. DSG service was flawless.', date: '2026-05-30' },
      { customerName: 'Sophie Laurent', rating: 5, comment: 'Brought my Audi A4 here. Professional team, transparent pricing, great result.', date: '2026-04-18' },
      { customerName: 'Bader Al-Muftah', rating: 4, comment: 'Good service, genuine parts. Waiting time is a bit long but worth it.', date: '2026-03-25' },
      { customerName: 'Nadia Petrov', rating: 5, comment: 'Carbon clean made a huge difference on my Golf GTI. Noticeable power improvement.', date: '2026-02-12' },
      { customerName: 'Ali Al-Dosari', rating: 4, comment: 'Authorised service for my VW. Professional staff, clean facility.', date: '2026-01-22' },
    ],
    promotions: [
      { id: 'qauto-dsg-offer', title: 'DSG + Oil Service Bundle', description: 'Book DSG gearbox service and get oil service at 50% off — valid on VW & Audi.', discount: '50% Oil', code: 'QAUTO-DSG', startDate: '2026-06-01', endDate: '2026-08-31' },
    ],
  },
];

// Booking IDs use a timestamp suffix so re-runs don't conflict with old docs
const TS = Date.now().toString(36);
const BOOKINGS = [
  { id: `bk_lc_aab_${TS}`, userId: CUSTOMER_ID, vendorId: 'vendor_aab_toyota', vendorName: 'AAB Toyota Main Service Center', carId: CAR_LAND_CRUISER, serviceName: '60,000 km Major Service', bookingDate: new Date(Date.now() + 86400000 * 3), status: 'Confirmed', cost: 2200, notes: 'First major service since purchase.' },
  { id: `bk_camry_tsc_${TS}`, userId: CUSTOMER_ID, vendorId: 'vendor_teyseer', vendorName: 'Teyseer Service Centre', carId: CAR_CAMRY, serviceName: 'Express Oil & Filter Change', bookingDate: new Date(Date.now() + 86400000 * 7), status: 'Confirmed', cost: 280, notes: 'Regular oil change.' },
  { id: `bk_patrol_${TS}`, userId: CUSTOMER_ID, vendorId: 'vendor_nissan_service', vendorName: 'Nissan Authorised Service Centre', carId: CAR_PATROL, serviceName: 'Patrol/Pathfinder AC Service', bookingDate: new Date(Date.now() - 86400000 * 14), status: 'Completed', cost: 550, notes: 'AC stopped blowing cold.' },
  { id: `bk_lc_tsc_${TS}`, userId: CUSTOMER_ID, vendorId: 'vendor_teyseer', vendorName: 'Teyseer Service Centre', carId: CAR_LAND_CRUISER, serviceName: 'Full Car Detailing', bookingDate: new Date(Date.now() - 86400000 * 45), status: 'Completed', cost: 1500, notes: 'Detailing before Eid.' },
  { id: `bk_camry_mana_${TS}`, userId: CUSTOMER_ID, vendorId: 'vendor_al_mana_ford', vendorName: 'Al Mana Ford & Lincoln Service', carId: CAR_CAMRY, serviceName: 'Four-Wheel Alignment & Balancing', bookingDate: new Date(Date.now() - 86400000 * 60), status: 'Completed', cost: 250, notes: 'Steering felt off after pothole.' },
];

// ── Firestore REST write (bypasses client SDK auth checks) ───────────────────
const BASE_URL = `https://firestore.googleapis.com/v1/projects/${PROJECT_ID}/databases/(default)/documents`;

function fsVal(v) {
  if (v === null || v === undefined) return { nullValue: null };
  if (typeof v === 'boolean') return { booleanValue: v };
  if (v instanceof Date) return { timestampValue: v.toISOString() };
  if (typeof v === 'number') return Number.isInteger(v) ? { integerValue: String(v) } : { doubleValue: v };
  if (typeof v === 'string') return { stringValue: v };
  if (Array.isArray(v)) return { arrayValue: { values: v.map(fsVal) } };
  if (typeof v === 'object') {
    return { mapValue: { fields: Object.fromEntries(Object.entries(v).map(([k, val]) => [k, fsVal(val)])) } };
  }
  return { stringValue: String(v) };
}

async function fsWrite(path, data, token) {
  const fields = Object.fromEntries(Object.entries(data).map(([k, v]) => [k, fsVal(v)]));
  const mask = Object.keys(fields).map(k => `updateMask.fieldPaths=${encodeURIComponent(k)}`).join('&');
  const url = `${BASE_URL}/${path}?${mask}&key=${API_KEY}`;
  const headers = { 'Content-Type': 'application/json' };
  if (token) headers['Authorization'] = `Bearer ${token}`;
  const res = await fetch(url, { method: 'PATCH', headers, body: JSON.stringify({ fields }) });
  if (!res.ok) {
    const body = await res.json().catch(() => ({}));
    const msg = body?.error?.message || res.statusText;
    throw new Error(`[${res.status}] ${msg}`);
  }
}

async function seed() {
  console.log(`\nQarWheel seed — project: ${PROJECT_ID}\n`);

  // Sign in to get an ID token for writes that require isSignedIn()
  let token = null;
  try {
    let cred;
    try {
      cred = await signInWithEmailAndPassword(auth, 'seed.admin@qarwheel.internal', 'QarWheelSeed2026!');
    } catch {
      cred = await createUserWithEmailAndPassword(auth, 'seed.admin@qarwheel.internal', 'QarWheelSeed2026!');
    }
    token = await cred.user.getIdToken();
    console.log('✓ Authenticated as seed user\n');
  } catch (e) {
    console.warn(`⚠  Auth failed (${e.message}) — will attempt unauthenticated writes\n`);
  }

  // ── Vendors ────────────────────────────────────────────────────────────────
  console.log('── Vendors ───────────────────────────────────');
  for (const vendor of VENDORS) {
    const vendorDoc = { ...vendor.data, createdAt: new Date(), updatedAt: new Date() };
    try {
      await fsWrite(`vendors/${vendor.id}`, vendorDoc, null);  // try unauthenticated first
    } catch {
      try { await fsWrite(`vendors/${vendor.id}`, vendorDoc, token); } catch (e2) {
        console.warn(`  ✗ vendor root ${vendor.id}: ${e2.message}`);
      }
    }
    for (const s of vendor.services) {
      const { id, ...d } = s;
      try { await fsWrite(`vendors/${vendor.id}/services/${id}`, d, token); } catch { /* ok */ }
    }
    for (const item of vendor.inventory) {
      const { id, ...d } = item;
      try { await fsWrite(`vendors/${vendor.id}/inventory/${id}`, d, token); } catch { /* ok */ }
    }
    for (let i = 0; i < vendor.reviews.length; i++) {
      try { await fsWrite(`vendors/${vendor.id}/reviews/review_${i + 1}`, vendor.reviews[i], token); } catch { /* ok */ }
    }
    for (const promo of vendor.promotions) {
      const { id, ...d } = promo;
      try { await fsWrite(`vendors/${vendor.id}/promotions/${id}`, d, token); } catch { /* ok */ }
    }
    console.log(`  ✓ ${vendor.data.name}`);
  }

  // ── Customer ───────────────────────────────────────────────────────────────
  console.log('\n── Customer ──────────────────────────────────');
  try {
    await fsWrite(`users/${CUSTOMER_ID}`, { firstName: 'Walid', lastName: 'Al-Mansouri', email: 'walid.almansouri@demo.qarwheel.qa', phoneNumber: '+97450123456', role: 'customer', createdAt: new Date(), updatedAt: new Date() }, token);
    console.log('  ✓ user: Walid Al-Mansouri');
  } catch (e) { console.warn(`  ✗ user: ${e.message}`); }

  const cars = [
    { id: CAR_LAND_CRUISER, vin: 'JTMCY7AJ1M4100001', make: 'Toyota', model: 'Land Cruiser', year: 2022, licensePlate: 'Qatar 2026 A', color: 'Pearl White', engineType: 'V8 Gasoline', currentMileage: 42000 },
    { id: CAR_CAMRY, vin: '4T1BF3EK2AU123456', make: 'Toyota', model: 'Camry', year: 2020, licensePlate: 'Qatar 8845 B', color: 'Midnight Black', engineType: '2.5L Inline-4 Gasoline', currentMileage: 58000 },
    { id: CAR_PATROL, vin: 'JN1TBNT32A0123456', make: 'Nissan', model: 'Patrol', year: 2021, licensePlate: 'Qatar 3312 C', color: 'Desert Sand', engineType: 'V8 4.0L Gasoline', currentMileage: 32000 },
  ];
  for (const car of cars) {
    const { id, ...d } = car;
    try {
      await fsWrite(`users/${CUSTOMER_ID}/cars/${id}`, { ...d, userId: CUSTOMER_ID, lastMileageUpdateDate: new Date().toISOString(), createdAt: new Date(), updatedAt: new Date() }, token);
      console.log(`  ✓ car: ${d.year} ${d.make} ${d.model}`);
    } catch (e) { console.warn(`  ✗ car ${id}: ${e.message}`); }
  }

  // ── Bookings — client SDK with serverTimestamp (rules need auth.uid == userId)
  console.log('\n── Bookings ──────────────────────────────────');
  const { setDoc: sdkSetDoc, doc: sdkDoc, serverTimestamp: sdkTs } = await import('firebase/firestore');
  for (const b of BOOKINGS) {
    const { id, ...d } = b;
    try {
      await sdkSetDoc(sdkDoc(db, 'bookings', id), { ...d, createdAt: sdkTs(), updatedAt: sdkTs() });
      console.log(`  ✓ ${b.serviceName} @ ${b.vendorName}`);
    } catch (e) { console.warn(`  ✗ booking ${id}: ${e.message}`); }
  }

  console.log('\nDone.\n');
  console.log('If vendor root docs showed ✗, go to Firebase Console → Firestore and');
  console.log('add the vendors manually, or temporarily set rules to allow write: if true;');
  console.log('then re-run this script.\n');
  process.exit(0);
}

seed().catch(e => { console.error(e); process.exit(1); });
